ProjectFive/ProjectFive/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from in_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('in_app/',include('in_app.urls')),
    path('log_out/',views.log_out,name='log_out'),
]

ProjectFive/in_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from in_app import views

app_name='in_app'

urlpatterns = [
    path('other/',views.other,name='other'),
    path('register/',views.register,name='register'),
    path('log_in/',views.log_in,name='log_in'),
    path('special/',views.special,name='special'),
    path('goodbye/',views.goodbye,name='goodbye'),
    path('log_out/',views.log_out,name='logout'),
]

ProjectFive/in_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    #Add additional attributes

    profolio_site=models.URLField(blank=True)
    profile_pics=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

ProjectFive/in_app/forms.py
from django import forms
from in_app.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):

    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileForm(forms.ModelForm):

    class Meta():
        model=UserProfileInfo
        fields=('profolio_site','profile_pics')

ProjectFive/in_app/views.py
from django.shortcuts import render
from in_app.forms import UserForm,UserProfileForm
# Create your views here.

def index(request):
    return render(request,'in_app/base.html')

def other(request):
    total=0
    if request.method=='POST':
        value01=request.POST['value01']
        value02=request.POST['value02']
        total=int(value01)+int(value02)

    return render(request,'in_app/other.html',{'total':str(total)})

def register(request):

    registered=False

    if request.method=='POST':

        user_form=UserForm(request.POST)
        profile_form=UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pics' in request.FILES:
                profile.profile_pics=request.FILES['profile_pics']

            profile.save()
            registered=True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form=UserForm()
        profile_form=UserProfileForm()

    return render(request,'in_app/register.html',{'user_form':user_form,
                                                    'profile_form':profile_form,
                                                    'registered':registered})


from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout


def log_in(request):

    if request.method=='POST':

        username=request.POST.get('Username')
        password=request.POST.get('Password')

        user=authenticate(username=username,password=password)

        if user:

            if user.is_active:

                login(request,user)
                return HttpResponseRedirect(reverse('in_app:special'))

            else:
                return HttpResponse("Account isn't activated")
        else:
            print('Someone tried to login failed!')
            print(f"username:{username} and password:{password}")
            return HttpResponse('Invalid login details supplied')

    else:
        return render(request,'in_app/log_in.html')


def special(request):
    return render(request,'in_app/special.html')

def goodbye(request):
    return render(request,'in_app/goodbye.html')

@login_required
def log_out(request):

    logout(request)
    return HttpResponseRedirect(reverse('in_app:goodbye'))

ProjectFive/templates/in_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">Django</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'in_app:other' %}">Other <span class="sr-only">(current)</span></a>
            <a class="nav-link" href="{% url 'in_app:register' %}">Register</a>
            {% if user.is_authenticated %}
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                  <a class="nav-link" href="{% url 'log_out' %}">Logout</a>
                </div>

            {% else %}
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                  <a class="nav-link" href="{% url 'in_app:log_in' %}">Login</a>
                </div>
            {% endif%}
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </div>
        </div>
    </nav>


    {% block body_block%}
    <div class="container ">
      <div class="jumbotron">
        <h1>Welcome to Django Web</h1>
        <br>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </div>
    {% endblock%}



    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

ProjectFive/templates/in_app/goodbye.html
<!DOCTYPE html>

{% extends 'in_app/base.html' %}

{% block body_block%}
 <div class="container">
   <div class="jumbotron">
    {% csrf_token%}
     <h1>Goodbye! {{user.get_username}} </h1>
     <h3>See you next time.</h3>
   </div>
 </div>
{% endblock%}

ProjectFive/templates/in_app/log_in.html
<!DOCTYPE html>

{% extends 'in_app/base.html'%}

{% block body_block%}
<div class="container">
  <div class="jumbotron">
    <form  action="{% url 'in_app:log_in' %}" method="POST">
      {% csrf_token%}
      <h1>Please login!</h1>
      <br>
       <div class="form-group col-md-6">
         <label for="Username" >Username:</label>
         <input type="text" class="form-control" name="Username" placeholder="Enter username" >
         <small id='help' class='form-text text-muted'>Please don't repeat the same username</small>
      </div>

      <div class="form-group col-md-6">
        <label for="Password" >Password:</label>
        <input type="password" class="form-control" name="Password" placeholder="Password">
      </div>


      <input type="submit"  class='btn btn-primary' value="Login">

    </form>

  </div>

</div>

{% endblock%}

ProjectFive/templates/in_app/other.html
<!DOCTYPE html>

{% extends 'in_app/base.html' %}

{% block body_block%}

  <div class="container">
    <div class="jumbotron">
      <form method="POST">
        {% csrf_token %}
        <input type="number" name="value01">
        <input type="number" name="value02">
        <input type="submit" value="Submit">
        <br>
        <p>Total:</p>
        {{total}}
      </form>

    </div>
  </div>

{% endblock%}

ProjectFive/templates/in_app/register.html
<!DOCTYPE html>

{% extends 'in_app/base.html' %}

{% load crispy_forms_tags %}


{% block body_block%}
<div class="container">
  <div class="jumbotron">

    {% if registered %}
    <h1>Thank you for registering</h1>

    {% else %}
    <h1>Register</h1>
    <h3>Please fill the form:</h3>
    <form method="POST"  enctypr='multimedia/form-data'>
      <div class="col-5">
        {% csrf_token%}
        {{user_form|crispy}}
        {{profile_form|crispy}}
        <input type="Submit" class="btn btn-primary" value="Register">
      </div>
    </form>
    {% endif%}
  </div>
</div>
{% endblock%}

ProjectFive/templates/in_app/special.html
<!DOCTYPE html>

{% extends 'in_app/base.html' %}

{% block body_block%}
 <div class="container">
   <div class="jumbotron">
    {% csrf_token%}
     <h1>Welcome {{user.get_username}}! </h1>
   </div>
 </div>
{% endblock%}